In [15]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [17]:
from os import X_OK
x=df.drop(['diagnosis','Unnamed: 32'],axis=1)
y=df['diagnosis']
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [18]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
y_train

564    M
325    B
135    M
98     B
288    B
      ..
290    B
33     M
335    M
473    B
312    B
Name: diagnosis, Length: 455, dtype: object

In [20]:
y_train = LabelEncoder().fit_transform(y_train)
y_test = LabelEncoder().fit_transform(y_test)

In [21]:
y_train

array([1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,

## Np array to Pytorch tensors

In [22]:
x_tr_ten=torch.from_numpy(X_train)
x_te_ten=torch.from_numpy(X_test)
y_tr_ten=torch.from_numpy(y_train)
y_te_ten=torch.from_numpy(y_test)

In [23]:
x_tr_ten

tensor([[-0.2385,  2.1264,  0.7050,  ...,  1.6593, -1.4022, -0.7101],
        [ 0.4614, -0.4195, -0.4655,  ..., -0.9111, -0.3440, -0.8421],
        [-0.2390, -0.3909,  0.7234,  ..., -0.3322, -0.1064, -0.1568],
        ...,
        [ 0.4632,  0.8377,  0.3854,  ...,  1.0554, -0.4535, -0.4288],
        [-0.1738, -0.5341,  2.4482,  ..., -1.7808, -0.8141, -0.9263],
        [ 0.4604, -0.3937, -1.3692,  ..., -0.4751, -0.5529, -0.0487]],
       dtype=torch.float64)

# Define model

In [24]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_tr_ten * torch.log(y_pred) + (1 - y_tr_ten) * torch.log(1 - y_pred)).mean()
    return loss




## IMP parameter

In [25]:

learning_rate=0.1
epochs=10

## Training Pipeline

In [26]:
model =MySimpleNN(x_tr_ten)
# define loops
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(x_tr_ten)


  # calculate loss
  loss = model.loss_function(y_pred, y_tr_ten)

  # backward pass
  loss.backward()


  # update weights
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')


Epoch: 1, Loss: 3.8125091750891387
Epoch: 2, Loss: 3.695006073243025
Epoch: 3, Loss: 3.5721669343908578
Epoch: 4, Loss: 3.443835134996105
Epoch: 5, Loss: 3.310988876916482
Epoch: 6, Loss: 3.1730002754366167
Epoch: 7, Loss: 3.0345484897288704
Epoch: 8, Loss: 2.8966389572599893
Epoch: 9, Loss: 2.75690317480731
Epoch: 10, Loss: 2.6127612667005558


In [27]:
model.weights

tensor([[ 0.0578],
        [-0.1493],
        [ 0.2005],
        [ 0.7128],
        [ 0.1533],
        [-0.1249],
        [ 0.2313],
        [ 0.2723],
        [ 0.5648],
        [ 0.4986],
        [ 0.7347],
        [ 0.0064],
        [ 0.3555],
        [ 0.7805],
        [ 0.1260],
        [ 0.1265],
        [ 0.4134],
        [ 0.7967],
        [ 0.6717],
        [ 0.4902],
        [ 0.2573],
        [ 0.1567],
        [ 0.4922],
        [-0.1788],
        [ 0.0899],
        [-0.1056],
        [ 0.5012],
        [ 0.3332],
        [ 0.3952],
        [ 0.5145],
        [ 0.4638]], dtype=torch.float64, requires_grad=True)

In [28]:
model.bias

tensor([-0.0164], dtype=torch.float64, requires_grad=True)

# Evaluation

In [29]:
with torch.no_grad():
  y_pred = model.forward(x_te_ten)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_te_ten).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5260080099105835
