In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
import torch
import torch.nn as nn

class Model (nn.Module):
  def __init__(self,num_features):

    super().__init__() # invoking nn constructor inheritance concept
    self.Linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,features):
    out=self.Linear(features)
    out=self.sigmoid(out)
    return out

In [3]:
features = torch.rand(10,5) # 5 features
# create model
model=Model(features.shape[1])
# fw pass
model(features)

tensor([[0.5784],
        [0.5935],
        [0.6509],
        [0.6318],
        [0.5241],
        [0.6163],
        [0.6006],
        [0.5400],
        [0.6487],
        [0.5161]], grad_fn=<SigmoidBackward0>)

In [4]:
model.Linear.weight

Parameter containing:
tensor([[ 0.2287, -0.2946,  0.4097,  0.0747,  0.4319]], requires_grad=True)

In [5]:
model.Linear.bias

Parameter containing:
tensor([-0.0212], requires_grad=True)

In [6]:

!pip install torchinfo

In [7]:
from torchinfo import summary
summary(model, input_size=(10,5))


Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [8]:
class Model1(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.Linear1=nn.Linear(num_features,3)
    self.Relu=nn.ReLU()
    self.Linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,features):
    out=self.Linear1(features)
    out=self.Relu(out)
    out=self.Linear2(out)
    out=self.sigmoid(out)
    return out

In [9]:
features1 = torch.rand(10,5)

#create model
model1=Model1(features1.shape[1])
#fw pass
model1(features1)

tensor([[0.4130],
        [0.4130],
        [0.4130],
        [0.4090],
        [0.4104],
        [0.4130],
        [0.4130],
        [0.4109],
        [0.4130],
        [0.4130]], grad_fn=<SigmoidBackward0>)

In [10]:
model1.Linear1.weight

Parameter containing:
tensor([[-0.2616, -0.2692,  0.2297, -0.0333, -0.4050],
        [-0.1596,  0.2951,  0.0140,  0.2257, -0.2258],
        [-0.1928, -0.4012, -0.1577, -0.1954, -0.0845]], requires_grad=True)

In [11]:
model1.Linear2.bias

Parameter containing:
tensor([-0.3514], requires_grad=True)

In [12]:
from torchinfo import summary
summary(model1, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model1                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Sequential contianer

In [13]:
class Model2(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out=self.network(features)
    return out

In [14]:
features1 = torch.rand(10,5)

#create model
model2=Model2(features1.shape[1])
#fw pass
model2(features1)

tensor([[0.4033],
        [0.3814],
        [0.3828],
        [0.4202],
        [0.3914],
        [0.3679],
        [0.3743],
        [0.3827],
        [0.4153],
        [0.3970]], grad_fn=<SigmoidBackward0>)

In [15]:
from torchinfo import summary
summary(model2, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Define NN model

In [16]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [17]:
from os import X_OK
x=df.drop(['diagnosis','Unnamed: 32'],axis=1)
y=df['diagnosis']
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [18]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
y_train = LabelEncoder().fit_transform(y_train)
y_test = LabelEncoder().fit_transform(y_test)

In [20]:
x_tr_ten=torch.from_numpy(X_train).float()
x_te_ten=torch.from_numpy(X_test).float()
y_tr_ten=torch.from_numpy(y_train).float()
y_te_ten=torch.from_numpy(y_test).float()

In [21]:
class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.network =nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )

  def forward(self,features):
    out=self.network(features)

    return out

    # Calculate loss
    loss = -(y_tr_ten * torch.log(y_pred) + (1 - y_tr_ten) * torch.log(1 - y_pred)).mean()
    return loss

In [ ]:
'''class MySimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.Linear=nn.Linear(num_features,1)
    self.Sigmoid=nn.Sigmoid()
  def forward(self,features):
    out=self.Linear(features)
    out=self.Sigmoid(out)
    return out

    # Calculate loss
    loss = -(y_tr_ten * torch.log(y_pred) + (1 - y_tr_ten) * torch.log(1 - y_pred)).mean()
    return loss'''

In [26]:
loss_function=nn.BCELoss()

In [27]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [28]:

learning_rate=0.1
epochs=10

In [31]:
model3 =MySimpleNN(x_tr_ten.shape[1])
# define loops
for epoch in range(epochs):
  # forward pass
  y_pred = model3(x_tr_ten)


  # calculate loss
  loss = loss_function(y_pred, y_tr_ten.view(-1,1))
  # for reshaping as the shape of y_pred and y_tr_ten are different so we used view  or can use reshspe

  # backward pass
  loss.backward()


  # update weights
  with torch.no_grad():
    for param in model3.parameters():
      param -= learning_rate * param.grad


  # zero grad
  model3.zero_grad()


  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7374410629272461
Epoch: 2, Loss: 0.7092612385749817
Epoch: 3, Loss: 0.6818236708641052
Epoch: 4, Loss: 0.6551686525344849
Epoch: 5, Loss: 0.6290475726127625
Epoch: 6, Loss: 0.603288471698761
Epoch: 7, Loss: 0.5781400799751282
Epoch: 8, Loss: 0.5537264943122864
Epoch: 9, Loss: 0.5296628475189209
Epoch: 10, Loss: 0.5068525671958923


In [41]:
model3.network[0].weight

Parameter containing:
tensor([[ 0.0526, -0.1008, -0.0888, -0.0048,  0.2046,  0.0522,  0.1968,  0.0246,
          0.1664,  0.0486,  0.0653, -0.0949,  0.1273,  0.0484,  0.0554, -0.0748,
         -0.1034,  0.0230, -0.1213, -0.1671, -0.0416,  0.2018, -0.0918,  0.0624,
         -0.0693,  0.0771, -0.0711, -0.1038,  0.1520,  0.1046,  0.1643],
        [ 0.1266, -0.1382, -0.0456, -0.2029, -0.0918,  0.0655, -0.2022, -0.2473,
         -0.0529, -0.0806,  0.0231, -0.2032, -0.0922, -0.2325, -0.2200,  0.1431,
          0.1326, -0.0799, -0.0140, -0.1152, -0.0570, -0.2006, -0.0330,  0.0126,
         -0.1832,  0.0210,  0.0654,  0.0278, -0.0727, -0.2135, -0.1850],
        [-0.0772, -0.1810, -0.1114,  0.0272,  0.0223,  0.1360,  0.0457, -0.1700,
          0.0435,  0.0958,  0.0794, -0.1264,  0.0768,  0.0728,  0.1198, -0.1117,
          0.0109, -0.0767,  0.1530,  0.0054,  0.0480, -0.0701, -0.1874, -0.1178,
         -0.2311,  0.0272,  0.0158,  0.1168,  0.0926, -0.0789,  0.0707]],
       requires_grad=True)

In [40]:
model3.network[2].weight

Parameter containing:
tensor([[ 0.2739, -0.5943, -0.3965]], requires_grad=True)

# Torch.optim

In [43]:
model4 =MySimpleNN(x_tr_ten.shape[1])

# define optimizer
optimizer= torch.optim.SGD(model4.parameters(),lr=learning_rate)

# define loops
for epoch in range(epochs):

  # forward pass
  y_pred = model4(x_tr_ten)

  # calculate loss
  loss = loss_function(y_pred, y_tr_ten.view(-1,1))
  ''' for reshaping as the shape of y_pred and y_tr_ten
  are different so we used view  or can use reshspe'''

  # zero grad
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # update weights
  optimizer.step()



  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7314032316207886
Epoch: 2, Loss: 0.6978837847709656
Epoch: 3, Loss: 0.6670023202896118
Epoch: 4, Loss: 0.6379244327545166
Epoch: 5, Loss: 0.6101112961769104
Epoch: 6, Loss: 0.5834823846817017
Epoch: 7, Loss: 0.5577816367149353
Epoch: 8, Loss: 0.5326999425888062
Epoch: 9, Loss: 0.5084460973739624
Epoch: 10, Loss: 0.48517173528671265


In [45]:
with torch.no_grad():
  y_pred = model4.forward(x_te_ten)
  y_pred = (y_pred > 0.8).float()
  accuracy = (y_pred == y_te_ten).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6357340812683105
