In [5]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification

In [14]:
# S 1: create a synthetic classification dataset
x,y = make_classification(
    n_samples=10,
    n_features =2,
    n_informative =2,
    n_redundant=0,
    n_classes=2,
    random_state=42
)

In [15]:
x

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [22]:
# Convert the data to PyTorch tensors
X = torch.tensor(x, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [23]:
from torch.utils.data import Dataset, DataLoader

In [24]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]
  def __getitem__(self, idx):
    return self.features[idx], self.labels[idx]

In [25]:
dataset= CustomDataset(x,y)


In [26]:
len(dataset)

10

In [28]:
dataset[0]

(array([ 1.06833894, -0.97007347]), tensor(1))

In [30]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)

In [31]:
for b_features,b_labels in dataloader:
    print(b_features)
    print(b_labels)
    print("-"*50)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]], dtype=torch.float64)
tensor([1, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [ 1.7774,  1.5116]], dtype=torch.float64)
tensor([0, 1])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [ 1.8997,  0.8344]], dtype=torch.float64)
tensor([1, 1])
--------------------------------------------------
tensor([[-0.5872, -1.9717],
        [ 1.7273, -1.1858]], dtype=torch.float64)
tensor([0, 1])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]], dtype=torch.float64)
tensor([0, 0])
--------------------------------------------------
