In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

In [7]:
from os import X_OK
x=df.drop(['diagnosis'],axis=1)
y=df['diagnosis']
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
y_train

258    M
473    B
143    B
418    B
407    B
      ..
494    B
420    B
41     M
132    M
387    B
Name: diagnosis, Length: 455, dtype: object

In [10]:
y_train = LabelEncoder().fit_transform(y_train)
y_test = LabelEncoder().fit_transform(y_test)

In [11]:
y_train

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,

## Np array to Pytorch tensors

In [28]:
x_tr_ten=torch.from_numpy(X_train)
x_te_ten=torch.from_numpy(X_test)
y_tr_ten=torch.from_numpy(y_train)
y_te_ten=torch.from_numpy(y_test)

In [29]:
y_te_ten

tensor([0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1,
        0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1])

In [51]:
from torch.utils.data import Dataset, DataLoader
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features=features
    self.labels=labels
  def __len__(self):
    return len(self.features)
  def __getitem__(self,idx):
    return self.features[idx],self.labels[idx]

In [52]:
tr_ds= CustomDataset(x_tr_ten,y_tr_ten)
te_ds=CustomDataset(x_te_ten,y_te_ten)

In [53]:
tr_ds[10]

(tensor([-0.7487,  0.4248, -0.7355, -0.7086,  0.9694, -0.1984, -0.5239, -0.6794,
          0.0625,  0.9979, -0.2711,  1.7062, -0.3585, -0.3226,  1.1708, -0.4568,
         -0.1868, -0.6701, -0.3063,  0.0895, -0.6389,  1.0988, -0.6580, -0.6130,
          1.0191, -0.5272, -0.4454, -0.7879, -0.2418,  0.2458],
        dtype=torch.float64),
 tensor(0))

In [54]:
tr_loader= DataLoader(tr_ds,batch_size=32,shuffle=True)
te_loader=DataLoader(te_ds,batch_size=32,shuffle=True)

# Define model

In [55]:
import torch
import torch.nn as nn

class MySimpleNN(nn.Module):
  def __init__(self,num_features):

    super().__init__() # invoking nn constructor inheritance concept
    self.Linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()
  def forward(self,features):
    out=self.Linear(features)
    out=self.sigmoid(out)
    return out

## IMP parameter

In [56]:

learning_rate=0.1
epochs=10

In [59]:
## construct model
model =MySimpleNN(x_tr_ten.shape[1])

#define optimizer
optimizer= torch.optim.SGD(model.parameters(),lr=learning_rate)

# define loss fn
loss_fn=nn.BCELoss()



## Training Pipeline

In [60]:
for epoch in range(epochs):
  for features, labels in tr_loader:
    # Forward pass
    outputs = model(features.float())
    loss = loss_fn(outputs, labels.view(-1,1).float())

    # Backward and optimize
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

  # Print loss for every epoch
  print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

Epoch [1/10], Loss: 0.3609
Epoch [2/10], Loss: 0.2509
Epoch [3/10], Loss: 0.1535
Epoch [4/10], Loss: 0.0571
Epoch [5/10], Loss: 0.1734
Epoch [6/10], Loss: 0.0605
Epoch [7/10], Loss: 0.3790
Epoch [8/10], Loss: 0.0692
Epoch [9/10], Loss: 0.0706
Epoch [10/10], Loss: 0.0723


In [62]:
print(model.Linear.weight)

Parameter containing:
tensor([[ 0.3106,  0.3611,  0.5045,  0.3042,  0.1471, -0.0426,  0.3693,  0.4517,
          0.2363, -0.1908,  0.5756,  0.1357,  0.3066,  0.4272, -0.1468, -0.0201,
         -0.0376,  0.0046, -0.1404, -0.3834,  0.4697,  0.4751,  0.5243,  0.4508,
          0.3323,  0.2621,  0.2227,  0.6439,  0.3194,  0.2346]],
       requires_grad=True)


In [64]:
model.Linear.bias

Parameter containing:
tensor([-0.4294], requires_grad=True)

# Evaluation

In [69]:
with torch.no_grad():
  y_pred = model.forward(x_te_ten.float())
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_te_ten).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.5344721674919128


In [74]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in te_loader:
        # Forward pass
        y_pred = model.forward(x_te_ten.float())
        y_pred = (y_pred > 0.5).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1,1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.5307
